### ISSUE TITLE
UnicodeDecodeError when pip install

### ISSUE THREAD

**Issue by kellyzz** [lxyu/pinyin#9] opened 2016-02-24 22:41 UTC
When trying to pip install pinyin,  error occurs: `UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 571: character maps to <undefined>` How to resolve this issue? Thanks

**Comment by alleluxia** [comment] 2016-05-09 22:57
I got an error like " UnicodeDecodeError: 'gbk' codec can't decode byte 0xa0 in position 557: illegal multibyte sequence".  wonder what the solution is.

**Comment by lxyu** [comment] 2016-05-10 08:57
@alleluxia can you provide a reproduce script? From the error info, I really doubt the exception was throw by `pinyin` lib, since there's nothing related to gbk codec inside.

**Comment by genepeng** [comment] 2016-05-15 03:29
I also got error "UnicodeDecodeError"

[root@iZ23m3uc829Z ~]# pip3 --version
pip 8.1.2 from /usr/local/lib/python3.5/site-packages (python 3.5)
[root@iZ23m3uc829Z ~]# pip3 install pinyin
Collecting pinyin
  Using cached pinyin-0.3.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-7l01s8y7/pinyin/setup.py", line 17, in <module>
        long_description=open('README.rst').read(),
      File "/usr/local/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 555: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-7l01s8y7/pinyin/

**Comment by genepeng** [comment] 2016-05-15 04:00
I fixed it, workaround is:
1. download the package to local, and unzip
2. change the line
`long_description=open('README.rst').read(),`
to something else, like
`long_description='fix UnicodeDecodeError',`

3. go to the unzipped package
```$ pip install .```bash

**Comment by lxyu** [comment] 2016-05-16 08:23
I think the problem may be the shell default encoding using `gbk` rather than `utf-8`.

You may want to check this link http://stackoverflow.com/questions/5306153/how-to-get-terminals-character-encoding

**Comment by yangxq** [comment] 2016-05-25 08:58
![qq 20160525162712](https://cloud.githubusercontent.com/assets/221055/15533094/8f7dd8c0-2295-11e6-8b46-c5014b9ff3fe.jpg)

Install pinyin fail on Windows. I cannot change the default encoding in Windows. Could you please change the setup.py to fix this issue?

**Comment by pvtodorov** [comment] 2016-07-08 17:54
@genepeng Your method saved me when trying to install another package. Thanks a bunch!

**Comment by lxyu** [comment] 2016-11-24 03:31
Should be fixed.

**Closed** 2016-11-24 03:31 UTC
